# Skill List from ckoverflow and Math.Stackexchange
skill_list=['pattern-recognition', 'opengl', 'c-sharp', 'ruby-on-rails', 'graph', 'fortran', 'matlab', 'multithreading', 'jquery', 'python', 'rake', 'powershell', 'neural-network', 'ms-access', 'linear-programming', 'lisp', 'set-theory', 'mapreduce', 'c++', 'parallel-programming', 'complexity-theory', 'calculus', 'statistical-inference', 'computer-vision', 'mysql', 'nonlinear-optimization', 'numerical-optimization', 'scala', 'algebra', 'functional-analysis', 'mahout', 'optimization', 'amazon-web-services', 'real-analysis', 'computational-geometry', 'javascript', 'ajax', 'apache', 'integer-programming', 'solr', 'search', 'vb', 'convex-optimization', 'text-mining', 's', 'swing', 'query-optimization', 'clojure', 'probability', 'haskell', 'linear-algebra', 'perl', 'maple', 'genetic-algorithm', 'statistics', 'java', 'combinatorics', 'automata', 'data-structures', 'numerical-methods', 'game-programming', 'scheme', 'discrete-optimization', 'c', 'hive', 'groovy', 'erlang', 'data-mining', 'image-processing', 'r', 'computation-theory', 'prolog', 'approximation-algorithms', 'actionscript', 'discrete-mathematics', 'number-theory', 'fsharp', 'measure-theory', 'regression', 'cassandra', 'asp.net', 'servlets', 'mathematica', 'hadoop', 'html', 'machine-learning', 'vhdl', 'bigdata', 'estimation-theory', 'jsp', 'sql', 'php', 'mathematical-modeling', 'algorithm', 'database', 'information-theory', 'django', 'oracle', 'coding-theory', 'formal-methods', 'graphics', 'finite-element-analysis', 'networks', 'information-retrieval', 'nlp', 'virtualization', 'differential-equations', 'computational-mathematics', 'time-series', 'programming-languages', 'visualization', 'compiler', 'mathematical-analysis', 'mathematical-physics', 'cryptography', 'software-engineering', 'operating-systems', 'stochastic-calculus', 'control-theory', 'bioinformatics', 'security', 'signal-processing', 'distributed-system', 'fluid-dynamics', 'chemistry', 'econometrics', 'artificial-intelligence', 'hci', 'game-theory', 'operations-research', 'functional-programming', 'data-modeling', 'ios', 'android', 'user-interface', 'formal-verification', 'lucene', 'nutch']

# Skill List for Languages from Dmoz
skill_list_dmoz_lang = ['Assembly', 'Awk', 'C', 'C++', 'Cg', 'Clojure', 'Cocoa', 'C-sharp', 'Erlang', 'Fortran', 'Groovy', 'Haskell', 'HTML', 'Java', 'JavaScript', 'Lisp', 'Maple', 'Mathematica', 'MATLAB', 'OCaml', 'Objective-C', 'Pascal', 'Perl', 'PHP', 'PLSQL', 'Prolog', 'Python', 'R', 'SAS', 'Scheme', 'SQL', 'Verilog', 'VHDL', 'Delphi', '.net', 'Flash']

# Skill List from Quant Stackexchange
skill_list_finance_stackoverflow = ['options', 'volatility', 'time-series', 'equities', 'fixed-income', 'statistics', 'interest-rates', 'backtesting', 'quant-trading-strategies', 'portfolio-management', 'trading', 'high-frequency', 'risk-management', 'market-data', 'optimization', 'fx', 'futures', 'monte-carlo', 'probability', 'regression', 'derivatives', 'stochastic-calculus', 'arbitrage', 'hedging', 'garch', 'yield-curve', 'swaps', 'market-microstructure', 'pairs-trading', 'machine-learning', 'capm', 'econometrics', 'numerical-methods', 'algorithmic-trading', 'american-options', 'forward', 'etf', 'credit', 'order-execution', 'visualization', 'exotics', 'financial-engineering', 'differential-equations', 'credit-ratings', 'asset-pricing', 'matlab']

skill_list_electrical_stackoverflow = ['arduino', 'microcontroller', 'power-supply', 'transistors', 'batteries', 'capacitor', 'pcb', 'usb', 'digital-logic','op-amp', 'fpga', 'mosfet', 'audio', 'voltage-regulator', 'amplifier', 'rf', 'serial', 'analog', 'integrated-circuit', 'wireless', 'ac', 'dc', 'transformer', 'verilog', 'diodes', 'c', 'vhdl', 'dc-motor', 'lcd', 'ethernet', 'bluetooth', 'raspberry-pi', 'antenna', 'inductor', 'solar-cell', 'oscilloscope', 'electromagnetism', 'wifi', 'infrared', 'xilinx', 'microprocessor', 'pcb-fabrication', 'low-power']

skill_list_job_description = ['css', 'linux', 'xml', 'json', 'j2ee', 'j2me', 'unix', 'mvc', 'spring', 'vmware', 'architecture', 'hibernate','ms-office', 'ms-excel', 'cisco', 'tcp', 'soap', 'rest', 'wcf', 'wpf','ssis', 'wan', 'lan', 'ldap', 'dns', 'dhcp', 'smtp', 'vpn', 'ssl', 'nas', 'olap', 'sharepoint', 'soa', 'erp', 'ssrs', 'jira', 'git', 'svn', 'nosql', 'selenium', 'jenkins', 'flash', 'linq', 'sccm', 'cms', 'eclipse', 'netbeans', 'javabeans', 'xcode', 'cocoa', 'maven', 'jsf', 'hbase', 'gwt', 'drupal', 'cloud',  'photoshop', 'adobe-illustrator', 'ospf', 'extjs','cad','visualforce', 'ant', 'waterfall', 'agile', 'bootstrap', 'foundation', 'magento', 'dreamweaver', 'jee', 'ms-project', 'wordpress', 'unit-testing', 'firmware', 'acceptance-testing', 'wsdl', 'loadrunner', 'openstack', 'xsl', 'mongodb', 'routing', 'visio', 'xslt', 'cognos', 'oop', 'firewall', 'sybase', 'solaris', 'junit', 'windows-server', 'salesforce', 'sap', 'sas', 'crm', 'iis', 'tomcat', 'citrix', 'lamp', 'jboss', 'san', 'nas', 'itil',  'node.js', 'backbone.js', 'cgi', 'jms', 'wireless', 'etl', 'sdlc', 'jdbc', 'data-warehouse', 'design-patterns', 'chef', 'puppet', 'iso', 'informatica', 'testing', 'qa', 'team-foundation-server', 'embedded', 'business-intelligence', 'autocad']

skill_list_new_learning = ['web-analytics', 'google-analytics', 'mixpanel', 'game-engine']

skill_list_server_fault = ["linux", "ubuntu", "windows", "centos", "nginx", "ssh", "debian", "amazon-ec2", "raid", "macosx", "emailserver", "cron", "postgresql", "samba", "storage", "hosting", "kvm-virtualization", "remote-desktop", "xen", "freebsd", "nat", "reverse-proxy", "nfs", "https", "bash", "proxy", "vmware-esxi", "redhat", "ip", "smtp", "ftp", "load-balancing", "vps", "hyper-v", "filesystems", "virtual-machines", "squid", "nagios", "virtualbox", "lvm", "fedora", "ipv6"]

skill_list_dba = ["database-design", "replication", "innodb", "index", "query-performance", "database-administration", "stored-procedures", "t-sql", "myisam", "db2"]

skill_list_physics = ["quantum-mechanics", "quantum-field-theory", "electromagnetism", "newtonian-mechanics", "general-relativity", "thermodynamics", "classical-mechanics", "special-relativity", "particle-physics", "optics", "fluid-dynamics", "energy", "string-theory", "cosmology", "astronomy", "mathematical-physics", "statistical-mechanics", "electromagnetic-radiation", "condensed-matter", "electricity", "black-holes", "electrostatics", "experimental-physics", "visible-light", "waves", "newtonian-gravity", "photons", "astrophysics", "nuclear-physics", "lagrangian-formalism", "angular-momentum", "kinematics", "spacetime", "heat", "differential-geometry", "solid-state-physics", "electric-circuits", "orbital-motion", "energy-conservation", "pressure", "quantum-gravity", "acoustics", "water", "supersymmetry", "symmetry", "temperature", "entropy", "spin", "momentum", "rotational-dynamics", "wavefunction", "friction", "schroedinger-equation", "quantum-electrodynamics", "magnetic-fields", "gauge-theory", "electrons", "conservation-laws", "electric-fields", "material-science", "hamiltonian-formalism", "quantum-interpretations", "conformal-field-theory", "radiation", "entanglement", "scattering", "space", "harmonic-oscillator", "planets", "uncertainty-principle", "space-expansion", "relativity", "current", "laser", "reflection", "semiconductor-physics"]

skill_list_crossvalidated = ["time-series", "hypothesis-testing", "logistic", "anova", "bayesian", "classification", "clustering", "data-visualization", "spss", "sampling", "pca", "generalized-linear-model", "multivariate-analysis", "svm", "predictive-models", "forecasting", "neural-networks", "stata", "feature-selection", "linear-model", "econometrics", "factor-analysis", "arima", "random-forest", "mcmc", "stochastic-processes", "inference", "nonlinear-regression", "markov-process", "likert", "kernel", "cart", "lasso"]

skill_list_biology = ["human-biology", "evolution", "genetics", "biochemistry", "molecular-biology", "neuroscience", "zoology", "cell-biology", "dna", "bioinformatics", "physiology", "botany", "homework", "microbiology", "proteins", "immunology", "pharmacology", "bacteriology", "plant-physiology", "entomology", "metabolism", "reproduction", "ecology", "molecular-genetics", "human-anatomy", "brain", "species-identification", "rna", "pathology", "eyes", "lab-techniques", "endocrinology", "dna-sequencing", "vision", "gene-expression", "food", "genomics", "cancer", "sleep", "enzymes", "human-genetics", "hematology", "gene", "digestive-system", "terminology", "senescence", "structural-biology", "photosynthesis", "virology", "cardiology", "ethology", "mathematical-models", "pcr", "cell-culture", "development", "chromosome", "biophysics", "taxonomy", "embryology", "natural-selection", "muscles", "nutrition", "synthetic-biology", "transcription", "behaviour", "cellular-respiration", "theoretical-biology", "mammals", "toxicology", "neurotransmitter", "plant-anatomy", "statistics", "experimental-design", "anatomy", "circadian-rhythms", "gel-electrophoresis", "genomes", "neuroanatomy", "mycology", "ornithology", "mutations", "pigmentation", "protocol", "epigenetics", "mitochondria", "ecoli", "perception", "nomenclature", "sensation", "amino-acids", "meiosis", "antibody", "software", "rna-sequencing", "neurology", "phylogenetics", "cell-membrane", "cloning", "mitosis", "microscopy", "human-genome", "marine-biology", "skin", "translation", "life", "book-recommendation", "history", "virus"]

skill_list_chemistry = ["organic-chemistry", "physical-chemistry", "inorganic-chemistry", "homework", "everyday-chemistry", "thermodynamics", "acid-base", "electrochemistry", "reaction-mechanism", "water", "equilibrium", "bond", "biochemistry", "redox", "molecules", "ions", "synthesis", "computational-chemistry", "home-experiment", "nomenclature", "energy", "aqueous-solution", "safety", "atoms", "ph", "kinetics", "solubility", "experimental-chemistry", "quantum-mechanics", "electronic-configuration", "electrons", "crystalline-structure", "coordination-compounds", "theoretical-chemistry", "analytical-chemistry", "polymers", "orbitals", "gas-laws", "metal", "spectroscopy", "periodic-table", "aromatic-compounds", "materials", "solvents", "quantum-chemistry", "combustion", "hydrogen", "experimental-technique", "software", "plastics", "heat", "periodic-trends", "covalent-compounds", "enthalpy", "terminology", "solid-state-chemistry", "stability", "crystal", "food-chemistry", "molecular-orbitals", "purification", "nmr", "hybridization", "surface-chemistry", "structural-diagrams", "stoichiometry", "toxicity", "solutions", "phase", "free-energy", "ionic-compounds", "chemical-biology", "stereoisomerism", "transition-metals", "bonding", "color", "catalysis", "intermolecular-forces", "mixtures", "mole", "boiling-point", "resonance", "electrolysis", "nanotechnology", "nuclear", "optical-properties", "medicinal-chemistry", "mass-spectrometry", "melting-point", "history-of-chemistry", "carbonyl-compounds", "surfactants", "stereochemistry", "vsepr-theory", "extraction", "identification", "fuel", "electron-affinity", "chirality", "symmetry", "structural-biology", "volumetric-analysis", "temperature", "chromatography", "conformers", "model", "polarity", "organometallic-compounds"]

skill_list_cs = ["linear-programming", "concurrency", "neural-networks", "game-theory", "information-theory", "number-theory", "memory-management", "greedy-algorithms", "quantum-computing", "network-flow",  "lambda-calculus", "parallel-computing", "type-theory", "randomized-algorithms", "formal-languages", "algorithm-analysis", "turing-machines", "regular-languages", "context-free", "automata", "finite-automata", "formal-grammars", "computational-geometry", "artificial-intelligence", "operating-systems", "computer-architecture", "dynamic-programming"]

#import itertools
#for comb in itertools.permutations(skill_list,2):
#	if comb[0]==comb[1]:
#		print "Same " + comb[0] + " " + comb[1]
#	if comb[0]==comb[1]+"s":
#		print "Extra s " + comb[0] + " " + comb[1]
#	if (comb[0] in comb[1]) and len(comb[0])>=3:
#		print "Almost same " + comb[0] + " " + comb[1]
#	if comb[0].replace('theory','').replace('-','')==comb[1].replace('theory','').replace('-',''):
#		print "Same " + comb[0] + " " + comb[1]	
#	if comb[0].replace('theory','').replace('-','')==comb[1].replace('theory','').replace('-','')+"s":
#		print "Extra s " + comb[0] + " " + comb[1]

skill_list = skill_list + skill_list_finance_stackoverflow + skill_list_dmoz_lang + skill_list_job_description + skill_list_electrical_stackoverflow + skill_list_new_learning + skill_list_server_fault + skill_list_dba + skill_list_crossvalidated + skill_list_cs
skill_list = list(set(map(lambda x: x.lower().replace(' ','-'), skill_list)))

